#!/bin/bash
#PBS -l select=24:kind=thin
#PBS -l walltime=10:00:00
#PBS -q dssc

cd $PBS_O_WORKDIR
module load openmpi/4.0.3/gnu/9.3.0

for ksize in 11 31; do
for procs in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 ; do
echo "executing on ", ${procs}, "  processors"
mpirun  --mca btl '^openib' -np ${procs} blur.mpi earth-notsolarge 1 ${ksize} ${ksize} 0.2 >mpi_strong_thin_${ksize}x${ksize}.${procs}
done
done
exit
