#!/bin/bash
#PBS -l select=24:kind=thin
#PBS -l walltime=10:00:00
#PBS -q dssc
 
cd $PBS_O_WORKDIR

for ksize in 11 31; do
for threads in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 ; do
./blur.omp image_${threads} 1 ${ksize} ${ksize} 0.2 ${threads} >omp_weak_thin_${ksize}x${ksize}.${threads}
done
done
exit